import Link from "next/link";
import { redirect } from "next/navigation";
import { AudioLines, ListChecks, Scissors, Search, Sparkles, Upload } from "lucide-react";
import { TryDemoButton } from "@/components/try-demo-button";
import { Button } from "@/components/ui";
import { getUser } from "@/lib/supabase/server";

const FEATURES = [
  {
    icon: AudioLines,
    title: "Playback locked to the transcript",
    body: "Every word is timestamped. Click a line to jump there, or watch the transcript follow along as it plays.",
  },
  {
    icon: Sparkles,
    title: "Summaries that switch shape",
    body: "The same call, read as a discovery call, a standup, or a customer interview. Switch template and the summary reorganises.",
  },
  {
    icon: ListChecks,
    title: "Action items with owners",
    body: "Pulled out with who agreed to do them, and a timestamp back to the moment they said it.",
  },
  {
    icon: Scissors,
    title: "Clips anyone can open",
    body: "Highlight a moment, send the link. It opens for people who were not on the call and have no account.",
  },
  {
    icon: Search,
    title: "Search across everything",
    body: "One query over every transcript you own, landing you at the exact second someone said it.",
  },
  {
    icon: Upload,
    title: "Bring recordings from anywhere",
    body: "A Zoom file a client emailed you, a voice memo, a webinar download. Drop it in and it is treated like any other meeting.",
  },
];

export default async function LandingPage() {
  if (await getUser()) redirect("/meetings");

  return (
    <div className="min-h-dvh bg-canvas">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5 sm:px-6">
        <div className="flex items-center gap-2">
          <div className="grid h-8 w-8 place-items-center rounded-lg bg-brand text-white">
            <AudioLines size={17} />
          </div>
          <span className="text-[15px] font-semibold tracking-tight">Cadence Notes</span>
        </div>
        <div className="flex items-center gap-2">
          <Link href="/login">
            <Button variant="ghost" size="sm">
              Sign in
            </Button>
          </Link>
          <Link href="/signup">
            <Button variant="secondary" size="sm">
              Create account
            </Button>
          </Link>
        </div>
      </header>

      <main>
        <section className="mx-auto max-w-3xl px-4 pt-16 pb-14 text-center sm:px-6 sm:pt-24">
          <p className="mb-5 inline-flex items-center gap-1.5 rounded-full border border-brand-line bg-brand-soft px-3 py-1 text-[12px] font-medium text-brand-ink">
            <Sparkles size={13} /> Every summary on this site was generated by an open-weight model
          </p>
          <h1 className="text-balance text-4xl font-semibold leading-[1.08] tracking-[-0.02em] sm:text-[56px]">
            Your meetings, written down and worth rereading.
          </h1>
          <p className="mx-auto mt-5 max-w-xl text-pretty text-[17px] leading-relaxed text-ink-soft">
            Cadence Notes joins your calls, records them, and gives you back a transcript you can
            search, a summary you can trust, and clips you can send to people who missed it.
          </p>
          <div className="mt-9 flex flex-col items-center gap-3">
            <TryDemoButton />
            <p className="text-[13px] text-ink-faint">
              No sign-up. Opens a workspace with five real meetings already in it.
            </p>
          </div>
        </section>

        <section className="mx-auto max-w-6xl px-4 pb-24 sm:px-6">
          <div className="grid gap-px overflow-hidden rounded-[var(--radius-card)] border border-line bg-line sm:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map(({ icon: Icon, title, body }) => (
              <div key={title} className="bg-surface p-6">
                <div className="mb-3.5 grid h-9 w-9 place-items-center rounded-[10px] bg-brand-soft text-brand-ink">
                  <Icon size={17} />
                </div>
                <h3 className="mb-1.5 text-[15px] font-semibold tracking-tight">{title}</h3>
                <p className="text-[13.5px] leading-relaxed text-ink-soft">{body}</p>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-6xl flex-col gap-2 px-4 py-6 text-[13px] text-ink-faint sm:flex-row sm:items-center sm:justify-between sm:px-6">
          <span>Built as a 24-hour rebuild of Fathom.</span>
          <a
            href="https://github.com/Anwaarhere27/fathom-clone"
            className="transition-colors hover:text-ink"
          >
            Source on GitHub
          </a>
        </div>
      </footer>
    </div>
  );
}
