"use client";

import { useState, useTransition } from "react";
import { Check, ChevronDown, Sparkles } from "lucide-react";
import { Badge, Spinner } from "@/components/ui";
import { cn, formatTimestamp } from "@/lib/utils";
import { TEMPLATE_LABELS, type Summary, type SummaryTemplate } from "@/lib/types";
import { generateSummary } from "@/app/(app)/meetings/[id]/actions";

const ORDER: SummaryTemplate[] = [
  "general",
  "sales_discovery",
  "customer_interview",
  "standup",
  "all_hands",
];

export function SummaryPanel({
  meetingId,
  summaries: initial,
  defaultTemplate,
  onSeek,
}: {
  meetingId: string;
  summaries: Summary[];
  defaultTemplate: SummaryTemplate;
  onSeek: (ms: number) => void;
}) {
  const [summaries, setSummaries] = useState(initial);
  const [template, setTemplate] = useState<SummaryTemplate>(defaultTemplate);
  const [open, setOpen] = useState(false);
  const [pending, startTransition] = useTransition();

  const current = summaries.find((s) => s.template === template);

  function choose(next: SummaryTemplate) {
    setTemplate(next);
    setOpen(false);
    if (summaries.some((s) => s.template === next)) return;

    // Not cached: generate on demand. Seeded meetings have every template
    // already, so this is the upload path.
    startTransition(async () => {
      const created = await generateSummary(meetingId, next);
      setSummaries((prev) => [...prev, created as Summary]);
    });
  }

  return (
    <div>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
        <div className="relative">
          <button
            onClick={() => setOpen((v) => !v)}
            className="flex items-center gap-2 rounded-[10px] border border-line bg-surface px-3 py-1.5 text-[13px] font-medium transition-colors hover:border-line-strong"
          >
            <Sparkles size={14} className="text-brand" />
            {TEMPLATE_LABELS[template]}
            <ChevronDown size={14} className={cn("text-ink-faint transition-transform", open && "rotate-180")} />
          </button>

          {open && (
            <>
              <div className="fixed inset-0 z-10" onClick={() => setOpen(false)} />
              <div className="absolute left-0 top-full z-20 mt-1.5 w-56 overflow-hidden rounded-[10px] border border-line bg-surface py-1 shadow-float">
                {ORDER.map((id) => (
                  <button
                    key={id}
                    onClick={() => choose(id)}
                    className={cn(
                      "flex w-full items-center justify-between px-3 py-1.5 text-left text-[13px] transition-colors hover:bg-sunken",
                      id === template && "font-medium text-brand-ink"
                    )}
                  >
                    {TEMPLATE_LABELS[id]}
                    {id === template && <Check size={14} />}
                  </button>
                ))}
              </div>
            </>
          )}
        </div>

        {current?.model && (
          <Badge tone="neutral" title="Every summary here is generated by an open-weight model">
            {current.model.replace("openai/", "")}
          </Badge>
        )}
      </div>

      {pending && !current ? (
        <div className="flex items-center gap-2 rounded-[var(--radius-card)] border border-line bg-sunken px-4 py-8 text-[13.5px] text-ink-soft">
          <Spinner /> Reading the transcript and writing a {TEMPLATE_LABELS[template].toLowerCase()}{" "}
          summary…
        </div>
      ) : !current ? (
        <p className="text-[13.5px] text-ink-faint">No summary yet.</p>
      ) : (
        <div className="space-y-5">
          {current.one_liner && (
            <p className="border-l-2 border-brand-line pl-3 text-[14.5px] leading-relaxed text-ink">
              {current.one_liner}
            </p>
          )}

          {current.sections.map((section) => (
            <section key={section.heading}>
              <h3 className="mb-2 text-[11px] font-semibold uppercase tracking-[0.06em] text-ink-faint">
                {section.heading}
              </h3>
              <ul className="space-y-1.5">
                {section.bullets.map((bullet, i) => (
                  <li key={i} className="flex gap-2.5">
                    <span
                      className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-ink-faint"
                      aria-hidden
                    />
                    <p className="flex-1 text-[13.5px] leading-[1.6] text-ink-soft">
                      {bullet.text}
                      {typeof bullet.start_ms === "number" && (
                        <button
                          onClick={() => onSeek(bullet.start_ms!)}
                          className="tnum ml-1.5 inline-flex rounded px-1 py-0.5 align-baseline text-[11.5px] font-medium text-brand-ink transition-colors hover:bg-brand-soft"
                          title="Jump to this moment"
                        >
                          {formatTimestamp(bullet.start_ms)}
                        </button>
                      )}
                    </p>
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>
      )}
    </div>
  );
}
